### ISSUE TITLE
XenAPI python module broken on 2.7.9

### ISSUE THREAD

**Issue by schplat** [xapi-project/xen-api#2100]
2.7.9 introduced SSL certificate verification be required in ssl.py

https://www.python.org/downloads/release/python-279/

This causes the following error when connecting to a Xenserver with it's default self-signed cert:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XenAPI.py", line 198, in <lambda>
    return lambda *params: self._login(name, params)
  File "XenAPI.py", line 164, in _login
    result = _parse_result(getattr(self, 'session.%s' % method)(*params))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by mseri** [comment]
The latest version of `XenAPI.py` allows to create a session passing `ignore_ssl=True`.

You can grab `XenAPI.py` from https://github.com/xapi-project/xen-api/tree/master/scripts/examples/python until it is released

**Comment by gaborigloi** [comment]
I've managed to get this to work on Ubuntu with the default `ignore_ssl=False`.
I've downloaded the default self-signed certificate of the server using `ssh root@<server> xe host-get-server-certificate uuid=<host UUID> > /tmp/<server>.pem`
Then I've added it by following https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate and selecting the new cert in the reconfigure screen. Now both python and curl recognize and use the self-signed cert 😄

**Comment by gaborigloi** [comment]
cc @thomasmck
