### ISSUE TITLE
Need help with Zabbix - XenAPI

### ISSUE THREAD

**Issue by Divyavi** [xapi-project/xen-api#4008]
Hi, 

I'm trying to monitor a xen server with the API and having following error. Can you please guide me to get it fixed?Zabbix 4.2

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/citrix.xenserver.py", line 497, in <module>
    main(sys.argv[1:])
  File "/usr/lib/zabbix/externalscripts/citrix.xenserver.py", line 480, in main
    refreshdatefiles(xenmaster, username, password, maxage)
  File "/usr/lib/zabbix/externalscripts/citrix.xenserver.py", line 296, in refreshdatefiles
    values = getStats(xenhosts, username, password, maxage)
  File "/usr/lib/zabbix/externalscripts/citrix.xenserver.py", line 195, in getStats
    page = getStatsXML(hostname, username, password, delay)
  File "/usr/lib/zabbix/externalscripts/citrix.xenserver.py", line 185, in getStatsXML
    pagehandle = urllib2.urlopen(theurl)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by edwintorok** [comment]
Are you able to connect to XenServer by other means? e.g. using `xe` or XenCenter and looking at the RRD graphs?
You can look at /var/log/xensource.log to see if there are any errors there.
