### ISSUE TITLE
Mysterious failure in HA with HOST_NOT_ENOUGH_FREE_MEMORY

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xen-api#4323]
Hi there!

So I'm reporting an issue I can easily reproduce in XCP-ng and CH 8.2. It's pretty easy to trigger, but the error message is completely… unrelated.

To trigger the issue, be sure to have:

1. HA enable at pool level
2. One VM not HA protected on a host

Now try to do a `host.evacuate`. It will fail with `HOST_NOT_ENOUGH_FREE_MEMORY`, regardless the amount of memory available. This **does not** happen if the VM is HA protected.

Obviously, we did the test on a 1GiB VM while having 100GiB+ free memory on all hosts.

We also have public reports about this: https://xcp-ng.org/forum/post/36829 but also private tickets reporting the same behaviour.

Here is a trace as an example (`host.restart` is doing `host.evacuate` anyway):

```
host.restart
{
  "id": "df35f1fe-ecba-4fb0-b4c6-1a9db0efac2b",
  "force": false
}
{
  "code": "HOST_NOT_ENOUGH_FREE_MEMORY",
  "params": [
    "OpaqueRef:a399f13f-ca17-44c7-a2de-4c25d0319293"
  ],
  "task": {
    "uuid": "48724829-015b-3de1-4542-5fb21b56fd12",
    "name_label": "Async.host.evacuate",
    "name_description": "",
    "allowed_operations": [],
    "current_operations": {},
    "created": "20210219T23:36:59Z",
    "finished": "20210219T23:36:59Z",
    "status": "failure",
    "resident_on": "OpaqueRef:f6b6a08e-f323-4883-82a4-7418a4780633",
    "progress": 1,
    "type": "<none/>",
    "result": "",
    "error_info": [
      "HOST_NOT_ENOUGH_FREE_MEMORY",
      "OpaqueRef:a399f13f-ca17-44c7-a2de-4c25d0319293"
    ],
    "other_config": {},
    "subtask_of": "OpaqueRef:NULL",
    "subtasks": [],
    "backtrace": "(((process xapi)(filename ocaml/xapi/xapi_host.ml)(line 560))((process xapi)(filename hashtbl.ml)(line 266))((process xapi)(filename hashtbl.ml)(line 272))((process xapi)(filename hashtbl.ml)(line 277))((process xapi)(filename ocaml/xapi/xapi_host.ml)(line 556))((process xapi)(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process xapi)(filename ocaml/xapi/rbac.ml)(line 231))((process xapi)(filename ocaml/xapi/server_helpers.ml)(line 103)))"
  },
  "message": "HOST_NOT_ENOUGH_FREE_MEMORY(OpaqueRef:a399f13f-ca17-44c7-a2de-4c25d0319293)",
  "name": "XapiError",
  "stack": "XapiError: HOST_NOT_ENOUGH_FREE_MEMORY(OpaqueRef:a399f13f-ca17-44c7-a2de-4c25d0319293)
    at Function.wrap (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_XapiError.js:16:12)
    at _default (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_getTaskResult.js:11:29)
    at Xapi._addRecordToCache (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:866:24)
    at forEach (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:887:14)
    at Array.forEach (<anonymous>)
    at Xapi._processEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:877:12)
    at Xapi._watchEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1038:14)"
}
```

**Comment by benjamreis** [comment]
So by design XAPi won't try to evacuate non HA protected VM.

But the error message is quite misleading: `HOST_NOT_ENOUGH_FREE_MEMORY`. IMHO a specific error message would be much better and more understable from a user POV. Something like `VM_NOT_HA_PROTECTED_CANT_EVACUATE`.

What do you think?
I think I talked about it with @psafont

**Comment by psafont** [comment]
I think having a specific message makes sense, flipping the what and the why in the name makes sense to me: `VM_CANT_EVACUATE_NOT_PROTECTED` @robhoes any better ideas on the name of the error?

**Comment by robhoes** [comment]
I think that we first need to understand where the error comes from. I wouldn't expect an error at all. A request to evacuate a host should just do that, regardless of the HA protection status of the VMs on that host.

**Comment by benjamreis** [comment]
I think the reasoning is when HA is enabled, you need to save RAM for HA protected VMs when evacuating.
From my understanding it was a conscious choice evn though imho you still should try to migrate other vms after the protected ones.

I 'll try to point at the code why the error is thrown error here but I need to search a bit as it was not easy to figure out.

**Comment by VGerris** [comment]
I still get this message on a recent 8.3 installation. It surprises me, because there is plenty of memory for all VMs on either host.  The error also does not show the host so it's cryptic in that way.
Perhaps an improvement could be that when HA is not enabled the memory would be calculated, or the error could be improved to indicate that HA is not enabled for a host ( and which one ).

**Comment by olivierlambert** [comment]
We can confirm the behavior with a recent report in here: https://xcp-ng.org/forum/topic/10247/server-will-not-migrate-vms-to-enter-maintenance-mode

In short:
* Manual Migrations work manually regardless of the VM HA state...
* Evacuate fails if anything but Restart is selected for the HA Mode.
  * Cluster in HA, VMs in best effort HA mode - Memory Error is thrown
  * Cluster in HA, VMs in disabled HA mode - Memory Error is thrown
  * Cluster in HA, VMs in restart HA mode - No Memory Error is thrown
* No HA: evacuate works.

**Comment by stormi** [comment]
So what would be the ideal behaviour here when evacuating a HA-protected host?

From a quick read, a naïve proposal:
- Migrate "restart HA" VMs first
- Attempt to migrate "best effort HA" VMs next
- Attempt to migrate "no HA" VMs next

... And handle migration failures or impossibilities the same way as with any other host evacuate command?

**Comment by nikade87** [comment]
Just ran in to this one, took a while to figure it out.
I think your suggestion @stormi is a good one, obviously it is annoying trying to figure out why you can't put the host in maintenance mode even tho it has a lot of free resources.

**Comment by MajorP93** [comment]
I can confirm that the issue still exists.
For now I switched all VMs that were using "best-effort" HA option to "restart" but it would be great if "best-effort" would not cause this issue.
Also like mentioned before some improved error logging would be great as "HOST_NOT_ENOUGH_FREE_MEMORY" is not really helpful for pinpointing the real, underlying issue.
