### ISSUE TITLE
XenAPI.py + python 3: TypeError: send_request() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by stormi** [xapi-project/xen-api#4767]
Opening this issue to discuss this bug in XenAPI.py when executed with python 3. Initially discussed at https://github.com/xenserver/guest-templates-json/pull/1#issuecomment-1179132574

Backtrace:
```
# python3 create-guest-templates 
Traceback (most recent call last):
  File "create-guest-templates", line 10, in <module>
    session.xenapi.login_with_password('', '', '', 'create-template')
  File "/usr/local/lib/python3.6/site-packages/XenAPI/XenAPI.py", line 269, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/site-packages/XenAPI/XenAPI.py", line 154, in xenapi_request
    self._login(methodname, params)
  File "/usr/local/lib/python3.6/site-packages/XenAPI/XenAPI.py", line 179, in _login
    getattr(self, 'session.%s' % method)(*params))
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
TypeError: send_request() takes 4 positional arguments but 5 were given
```

The bug is likely located at https://github.com/xapi-project/xen-api/blob/master/scripts/examples/python/XenAPI/XenAPI.py#L111 where a class that inherits `xmlrpc.client.Transport` redefines `send_request`.

`xmlrpc.client.Transport` doesn't have the same signature for `send_request` in python2 and python3, so a parameter is missing when called in python3. The backtrace is somewhat misleading as no mention of this function is made at all.

A similar issue is discussed at https://www.reddit.com/r/learnpython/comments/1l38mf/i_cant_get_xmlrpc_on_python_3_to_use_an_http_proxy/

@edwintorok wrote:
> XenAPI.py shouldn't override send_request, it should override make_connection instead, see https://stackoverflow.com/questions/11729159/use-python-xmlrpclib-with-unix-domain-sockets for some ideas.

**Comment by stormi** [comment]
Here's the code from xmlrpclib's python2 send_request:
```python
    def send_request(self, connection, handler, request_body):
        if (self.accept_gzip_encoding and gzip):
            connection.putrequest("POST", handler, skip_accept_encoding=True)
            connection.putheader("Accept-Encoding", "gzip")
        else:
            connection.putrequest("POST", handler)
```

And the overridden method in XenAPI.py:
```python
        connection.putrequest("POST", handler)
        for key, value in self._extra_headers:
            connection.putheader(key, value)
```

The difference is in the handling of the headers.

**Comment by edwintorok** [comment]
See `send_host`, it handles headers, I think we might be sending headers twice currently (but I haven't tried to confirm this with strace).

**Comment by stormi** [comment]
`make_connection` is already overridden, and the only reason `send_request` is overridden too is to handle extra headers added with `add_extra_headers`... Which does not seem to be used anywhere.

**Comment by stormi** [comment]
So the first simple thing that I'll try right now is to remove `send_request` and test.

**Comment by stormi** [comment]
The full implementation of UDSTransport is:
```python
class UDSTransport(xmlrpclib.Transport):
    def __init__(self, use_datetime=0):
        self._use_datetime = use_datetime
        self._extra_headers=[]
        self._connection = (None, None)
    def add_extra_header(self, key, value):
        self._extra_headers += [ (key,value) ]
    def make_connection(self, host):
        # Python 2.4 compatibility
        if sys.version_info[0] <= 2 and sys.version_info[1] < 7:
            return UDSHTTP(host)
        else:
            return UDSHTTPConnection(host)
    def send_request(self, connection, handler, request_body):
        connection.putrequest("POST", handler)
        for key, value in self._extra_headers:
            connection.putheader(key, value)
```

**Comment by stormi** [comment]
I guess I can also drop the python 2.4 compatibility

**Comment by stormi** [comment]
I'm still testing, but I'm having first good results with this:
```diff
diff --git a/scripts/examples/python/XenAPI/XenAPI.py b/scripts/examples/python/XenAPI/XenAPI.py
index 02c77b7c5..caa7002fb 100644
--- a/scripts/examples/python/XenAPI/XenAPI.py
+++ b/scripts/examples/python/XenAPI/XenAPI.py
@@ -92,26 +92,9 @@ class UDSHTTPConnection(httplib.HTTPConnection):
         self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
         self.sock.connect(path)
 
-class UDSHTTP(httplib.HTTPConnection):
-    _connection_class = UDSHTTPConnection
-
 class UDSTransport(xmlrpclib.Transport):
-    def __init__(self, use_datetime=0):
-        self._use_datetime = use_datetime
-        self._extra_headers=[]
-        self._connection = (None, None)
-    def add_extra_header(self, key, value):
-        self._extra_headers += [ (key,value) ]
     def make_connection(self, host):
-        # Python 2.4 compatibility
-        if sys.version_info[0] <= 2 and sys.version_info[1] < 7:
-            return UDSHTTP(host)
-        else:
-            return UDSHTTPConnection(host)
-    def send_request(self, connection, handler, request_body):
-        connection.putrequest("POST", handler)
-        for key, value in self._extra_headers:
-            connection.putheader(key, value)
+        return UDSHTTPConnection(host)
 
 def notimplemented(name, *args, **kwargs):
     raise NotImplementedError("XMLRPC proxies do not support python magic methods", name, *args, **kwargs)
```

There's no need to override the identical (in python2's xmlrpclib at least) `__init__()` method, nor `send_request()` as that's not where you're supposed to send the extra headers, as @edwintorok noted. 

We *could* keep the `add_extra_header()` method if it's useful, but it does not look like it is, at first sight.

**Comment by stormi** [comment]
Now this is interesting. There are 3 implementations of `UDSTransport` in the `xen-api` repository:
```
samuel@localhost:~/Vates/git/stormi/xen-api$ grep * -r -e "class UDSTransport" -A10
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py:class UDSTransport(xmlrpclib.Transport):
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-  def __init__(self, use_datetime = 0):
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-    self._use_datetime = use_datetime
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-    self._extra_headers = []
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-  def add_extra_header(self, key, value):
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-    self._extra_headers += [(key, value)]
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-  def make_connection(self, host):
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-    # Python 2.4 compatibility
ocaml/xcp-rrdd/scripts/rrdd/rrdd.py-    if sys.version_info[0] <= 2 and sys.version_info[1] < 6:
--
scripts/examples/python/XenAPI/XenAPI.py:class UDSTransport(xmlrpclib.Transport):
scripts/examples/python/XenAPI/XenAPI.py-    def __init__(self, use_datetime=0):
scripts/examples/python/XenAPI/XenAPI.py-        self._use_datetime = use_datetime
scripts/examples/python/XenAPI/XenAPI.py-        self._extra_headers=[]
scripts/examples/python/XenAPI/XenAPI.py-        self._connection = (None, None)
scripts/examples/python/XenAPI/XenAPI.py-    def add_extra_header(self, key, value):
scripts/examples/python/XenAPI/XenAPI.py-        self._extra_headers += [ (key,value) ]
scripts/examples/python/XenAPI/XenAPI.py-    def make_connection(self, host):
scripts/examples/python/XenAPI/XenAPI.py-        # Python 2.4 compatibility
scripts/examples/python/XenAPI/XenAPI.py-        if sys.version_info[0] <= 2 and sys.version_info[1] < 7:
scripts/examples/python/XenAPI/XenAPI.py-            return UDSHTTP(host)
--
scripts/templates/debian:class UDSTransport(xmlrpclib.Transport):
scripts/templates/debian-    def make_connection(self, host):
scripts/templates/debian-        return UDSHTTP(host)
scripts/templates/debian-
scripts/templates/debian-def xapi_local():
scripts/templates/debian-    return xmlrpclib.Server("http://_var_xapi_xapi/", transport=UDSTransport())
scripts/templates/debian-##### end hack.
scripts/templates/debian-
scripts/templates/debian-
scripts/templates/debian-class CommandException(Exception):
scripts/templates/debian-    pass
```

**Comment by edwintorok** [comment]
rrdd.py should probably reuse XenAPI.py where it can.

**Comment by stormi** [comment]
Found a use of `add_extra_header` in `sm`: https://github.com/xapi-project/sm/blob/master/drivers/SR.py#L121

**Comment by stormi** [comment]
> See `send_host`, it handles headers, I think we might be sending headers twice currently (but I haven't tried to confirm this with strace).

I can totally confirm that you were right. Extra headers are added twice currently (that, is, in the only use that I could find, `Subtask-of: something`).

Removing the overloaded `send_request` brings this back to one occurrence.

**Comment by edwintorok** [comment]
Please open a PR, looks like fixing this would address 2 things: avoid sending duplicate headers, *and* make the code more compatible with Python3, with no downsides discovered so far.
